data:
  home: ../../..
  dict: /code2seq/data/path_contexts/path_contexts.dict.c2s
  train: /m3yrin/code2seq/data/train
  valid: /m3yrin/code2seq/data/val1
  test: /m3yrin/code2seq/data/test

training:
  batch_size: 4
  num_epochs: 50
  lr: 0.001
  teacher_forcing_rate: 0.4
  nesterov: True
  weight_decay: 0.01
  momentum: 0.95
  decay_ratio: 0.95
  save_name: /model.pth
  warm_up: 1
  patience: 2

model:
  token_size: 512
  hidden_size: 64
  num_layers: 1
  bidirectional: True
  rnn_dropout: 0.5
  embeddings_dropout: 0.3
  num_k: 200

etc:
  info_prefix: code2seq
  slack_url_path: ../slack/slack_url.yml

comment: code2seq
